### PR TITLE
Fish 6435 fix dynamic proxy for context types

### PR DESCRIPTION
**Pull request by breakponchito**
This is a fix to enable the creation of Proxy classes for context Field injection instead of concrete classes. This PR include changes from @kalinchan added on the following : [PR for FISH-6285](https://github.com/payara/patched-src-jersey/pull/142) this was needed to run Payara Community and Payara Enterprise server 5.

### Testing Environment
ubuntu 20.04, maven 3.6.3, azul jdk 8

### CODE REVIEW

**Comment by breakponchito** [comment]
We need to wait until changes from @kalinchan  are accepted:[FISH-6285](https://github.com/payara/patched-src-jersey/pull/142). Then we just need to merge the changes to simplify this PR

**Review by Pandrex247 — COMMENTED** [review]
Could do with rebasing on top of the now updating maintenance branch (or at least merging it in).

Also this should be releasing as p1 not p2 - current maintenance is now on `p1-SNAPSHOT`

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Appears to break tests within `jersey-server` module.

```
[ERROR] org.glassfish.jersey.server.internal.process.ProxyInjectablesTest.testPerRequestContextInjected  Time elapsed: 0.069 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<class org.glassfish.jersey.server.internal.routing.UriRoutingContext> but was:<class com.sun.proxy.$Proxy122>

[ERROR] org.glassfish.jersey.server.internal.process.ProxyInjectablesTest.testBeanParam  Time elapsed: 0.041 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<class org.glassfish.jersey.server.RequestContextBuilder$TestContainerRequest> but was:<class com.sun.proxy.$Proxy117>

[ERROR] org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest.testReq  Time elapsed: 0.094 s  <<< ERROR!
java.util.concurrent.ExecutionException:
A MultiException has 3 exceptions.  They are:
1. java.lang.NullPointerException
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest$ReqResource errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest$ReqResource
```

**Comment by breakponchito** [comment]
> Appears to break tests within `jersey-server` module.
> 
> ```
> [ERROR] org.glassfish.jersey.server.internal.process.ProxyInjectablesTest.testPerRequestContextInjected  Time elapsed: 0.069 s  <<< ERROR!
> java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<class org.glassfish.jersey.server.internal.routing.UriRoutingContext> but was:<class com.sun.proxy.$Proxy122>
> 
> [ERROR] org.glassfish.jersey.server.internal.process.ProxyInjectablesTest.testBeanParam  Time elapsed: 0.041 s  <<< ERROR!
> java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<class org.glassfish.jersey.server.RequestContextBuilder$TestContainerRequest> but was:<class com.sun.proxy.$Proxy117>
> 
> [ERROR] org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest.testReq  Time elapsed: 0.094 s  <<< ERROR!
> java.util.concurrent.ExecutionException:
> A MultiException has 3 exceptions.  They are:
> 1. java.lang.NullPointerException
> 2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest$ReqResource errors were found
> 3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest$ReqResource
> ```

I already fixed the issues from the jersey-core-server, now the results looks like this:
[WARNING] Tests run: 923, Failures: 0, Errors: 0, Skipped: 11

**Comment by breakponchito** [comment]
unfortunately when I try to execute the whole tests I'm getting issues like the following:
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.099 s <<< FAILURE! - in org.glassfish.jersey.client.JerseyInvocationTest
[ERROR] org.glassfish.jersey.client.JerseyInvocationTest.overrideHttpMethodBasedComplianceCheckTest  Time elapsed: 0.052 s  <<< FAILURE!
I need to verify what to do with this test. Can you help me to check if on your side all the tests pass?

I tried  to test the branch jersey-2.36.payara-maintenance and I go the folllowing errors:
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.886 s - in org.glassfish.jersey.jdk.connector.HttpMethodTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SslFilterTLS11Test>SslFilterTest.testBasicEcho:70->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS11Test>SslFilterTest.testClientAuthentication:335->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS11Test>SslFilterTest.testCloseServer:133->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS11Test>SslFilterTest.testCustomHostameVerificationPass:320->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS11Test>SslFilterTest.testEcho100k:102->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS11Test>SslFilterTest.testRehandshakeClient:232->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS11Test>SslFilterTest.testRehandshakeServer:173->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS1Test>SslFilterTest.testBasicEcho:70->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS1Test>SslFilterTest.testClientAuthentication:335->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS1Test>SslFilterTest.testCloseServer:133->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS1Test>SslFilterTest.testCustomHostameVerificationPass:320->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS1Test>SslFilterTest.testEcho100k:102->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS1Test>SslFilterTest.testRehandshakeClient:232->SslFilterTest.openClientSocket:460 » SSLHandshake
[ERROR]   SslFilterTLS1Test>SslFilterTest.testRehandshakeServer:173->SslFilterTest.openClientSocket:460 » SSLHandshake
[INFO]
[ERROR] Tests run: 122, Failures: 0, Errors: 14, Skipped: 2

[INFO] jersey-connectors-jdk .............................. FAILURE [ 25.606 s]

**Comment by breakponchito** [comment]
Finally I did it build  using ZuluJDK 8  with the deletion of the tls protocols from the java.security file:
[INFO] Reactor Summary for jersey 2.36.payara-p1-SNAPSHOT:
[INFO]
[INFO] jersey ............................................. SUCCESS [  1.232 s]
[INFO] jersey-archetypes .................................. SUCCESS [  0.841 s]
....
[INFO] jersey-examples-sse-item-store-jersey-webapp ....... SUCCESS [  5.104 s]
[INFO] jersey-examples-sse-item-store-jaxrs-webapp ........ SUCCESS [ 15.083 s]
[INFO] jersey-examples-sse-twitter-aggregator ............. SUCCESS [  0.877 s]
[INFO] jersey-examples-system-properties .................. SUCCESS [  2.040 s]
[INFO] jersey-examples-moxy ............................... SUCCESS [  2.133 s]
[INFO] jersey-test-framework-maven-custom-enforcer-rules .. SUCCESS [  1.201 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] Total time:  39:00 min

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
