### PR TITLE
FISH-6670 FISH-6686 Upgrade Jersey to 2.37

### PR DESCRIPTION
**Pull request by arieki**
Re-apply patches from 2.36.payara-p1

### CODE REVIEW

**Comment by kalinchan** [comment]
Please upgrade ASM to version 9.4 https://github.com/arieki/patched-src-jersey/blob/ba4d41d995d3bca104d70251e68ac59627732419/pom.xml#L2151

As part of FISH-6686

**Comment by arieki** [comment]
> Please upgrade ASM to version 9.4 https://github.com/arieki/patched-src-jersey/blob/ba4d41d995d3bca104d70251e68ac59627732419/pom.xml#L2151
> 
> As part of FISH-6686

done https://github.com/payara/patched-src-jersey/pull/176/commits/8d2b73405ed32bebcb215ec1a28f4ee464bf9bf2
@kalinchan

**Comment by breakponchito** [comment]
Please upgrade copyrigths as needed

**Comment by arieki** [comment]
> Please upgrade copyrigths as needed

Resolved, please have a look @breakponchito

**Review by breakponchito — APPROVED** [review]
LGTM

**Pull request merged**
