### PR TITLE
FISH-6435: enable creation of proxy types instead of concrete classes

### PR DESCRIPTION
**Pull request by breakponchito**
This is a fix to enable the creation of Proxy classes for context Field injection instead of concrete classes.
### Testing Environment
ubuntu 20.04, maven 3.6.3, azul jdk 11

### CODE REVIEW

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Appears to break tests within `jersey-server` module.

(Copy pasted from the PR to the 2.36 branch, so don't trust the line numbers - the same 3 tests fail though)
```
[ERROR] org.glassfish.jersey.server.internal.process.ProxyInjectablesTest.testPerRequestContextInjected  Time elapsed: 0.069 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<class org.glassfish.jersey.server.internal.routing.UriRoutingContext> but was:<class com.sun.proxy.$Proxy122>

[ERROR] org.glassfish.jersey.server.internal.process.ProxyInjectablesTest.testBeanParam  Time elapsed: 0.041 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<class org.glassfish.jersey.server.RequestContextBuilder$TestContainerRequest> but was:<class com.sun.proxy.$Proxy117>

[ERROR] org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest.testReq  Time elapsed: 0.094 s  <<< ERROR!
java.util.concurrent.ExecutionException:
A MultiException has 3 exceptions.  They are:
1. java.lang.NullPointerException
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest$ReqResource errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest$ReqResource
```

**Comment by breakponchito** [comment]
> Appears to break tests within `jersey-server` module.
> 
> (Copy pasted from the PR to the 2.36 branch, so don't trust the line numbers - the same 3 tests fail though)
> 
> ```
> [ERROR] org.glassfish.jersey.server.internal.process.ProxyInjectablesTest.testPerRequestContextInjected  Time elapsed: 0.069 s  <<< ERROR!
> java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<class org.glassfish.jersey.server.internal.routing.UriRoutingContext> but was:<class com.sun.proxy.$Proxy122>
> 
> [ERROR] org.glassfish.jersey.server.internal.process.ProxyInjectablesTest.testBeanParam  Time elapsed: 0.041 s  <<< ERROR!
> java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<class org.glassfish.jersey.server.RequestContextBuilder$TestContainerRequest> but was:<class com.sun.proxy.$Proxy117>
> 
> [ERROR] org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest.testReq  Time elapsed: 0.094 s  <<< ERROR!
> java.util.concurrent.ExecutionException:
> A MultiException has 3 exceptions.  They are:
> 1. java.lang.NullPointerException
> 2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest$ReqResource errors were found
> 3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.internal.inject.ActiveBindingBindingTest$ReqResource
> ```

I already fixed the issues from the jersey-core-server, now the results looks like this:
[WARNING] Tests run: 927, Failures: 0, Errors: 0, Skipped: 11

**Comment by breakponchito** [comment]
unfortunately  when I try to execute the whole tests I'm getting issues like the following: 
ADVERTENCIA: Entity must be null for http method DELETE.
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.103 s <<< FAILURE! - in org.glassfish.jersey.client.JerseyInvocationTest
[ERROR] org.glassfish.jersey.client.JerseyInvocationTest.overrideHttpMethodBasedComplianceCheckTest  Time elapsed: 0.033 s  <<< FAILURE!
java.lang.AssertionError: ProcessingException expected.

I need to verify what to do with this test. Can you help me to check if on your side all the tests pass?

I tried to test the branch:   3.1.0-M7-BRANCH, and I got the same issue
ADVERTENCIA: Entity must be null for http method DELETE.
[ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.085 s <<< FAILURE! - in org.glassfish.jersey.client.JerseyInvocationTest
[ERROR] org.glassfish.jersey.client.JerseyInvocationTest.overrideHttpMethodBasedComplianceCheckTest  Time elapsed: 0.04 s  <<< FAILURE!
java.lang.AssertionError: ProcessingException expected.

**Comment by breakponchito** [comment]
now all tests are passing:
[INFO] jersey-examples-osgi-helloworld-webapp-wab ......... SUCCESS [  0.376 s]
[INFO] jersey-examples-osgi-helloworld-webapp-test ........ SUCCESS [  0.160 s]
[INFO] oauth-client-twitter ............................... SUCCESS [  0.122 s]
[INFO] jersey-examples-reload ............................. SUCCESS [  1.313 s]
[INFO] jersey-examples-rx-client-webapp ................... SUCCESS [ 18.814 s]
[INFO] jersey-examples-server-async ....................... SUCCESS [  3.085 s]
[INFO] jersey-examples-server-async-managed ............... SUCCESS [  2.971 s]
[INFO] jersey-examples-server-async-standalone ............ SUCCESS [  0.037 s]
[INFO] jersey-examples-server-async-standalone-client ..... SUCCESS [  0.228 s]
[INFO] jersey-examples-server-async-standalone-webapp ..... SUCCESS [  0.144 s]
[INFO] jersey-examples-server-sent-events-jaxrs ........... SUCCESS [  1.894 s]
[INFO] jersey-examples-servlet3-webapp .................... SUCCESS [  1.178 s]
[INFO] jersey-examples-simple-console ..................... SUCCESS [  1.650 s]
[INFO] jersey-examples-sse-item-store-jersey-webapp ....... SUCCESS [  4.338 s]
[INFO] jersey-examples-sse-item-store-jaxrs-webapp ........ SUCCESS [ 14.256 s]
[INFO] jersey-examples-sse-twitter-aggregator ............. SUCCESS [  0.242 s]
[INFO] jersey-examples-system-properties .................. SUCCESS [  1.339 s]
[INFO] jersey-examples-moxy ............................... SUCCESS [  1.534 s]
[INFO] jersey-test-framework-maven-custom-enforcer-rules .. SUCCESS [  0.462 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30:41 min

**Comment by Pandrex247** [comment]
You might need to shuffle the tag/snapshot commits around since you've got the tag before your additional fix, but all tests passed for me too 👍

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
