### PR TITLE
Added test for PR 3905

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
The JerseyTest has been altered to register logger  handlers before Weld is started in subclassed Setup method.

**Comment by arjantijms** [comment]
Sounds good! Does it now finally all work?

**Comment by jansupol** [comment]
Yes, it does, the test fails without the PR 3905.

**Comment by jansupol** [comment]
Well, after two fixes it should finally work :)

**Pull request closed without merging**
