### PR TITLE
FISH-6268 Upgrade google guava to version 29.0-jre

### PR DESCRIPTION
**Pull request by kalinchan**

### CODE REVIEW

**Review by Pandrex247 — COMMENTED** [review]
There's some failures in some of the unit tests I'm looking into - ClassNotFounds on Guava classes

**Review by Pandrex247 — COMMENTED** [review]
I've ran through quicklook and the Javaee7 samples (after editing dependencies to make sure they're using this version of Jersey as the client) and didn't run into issues, but the tests within Jersey itself fail on class not founds.

It looks like something isn't getting repackaged:

```
NoClassDefFoundError: Could not initialize class jersey.repackaged.com.google.common.util.concurrent.SettableFuture`
```

**Comment by kalinchan** [comment]
Made the relevant changes, however there is a failing unit test but I don't believe it is relevant to this PR

**Comment by kalinchan** [comment]
Should work now.

Built with `mvn clean install -Dexamples.excluded=true -Dtests.excluded=true -DskipTests`

I don't believe I have introduced any new failing tests. However there are some compilation errors in some examples that I won't resolve

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
